### ISSUE TITLE
Saludo de un compañero 

### ISSUE THREAD

**Issue by pxp9** [JLDEMIGUEL/Projects#1]
Hey qué tal , yo soy Pepe Márquez un compañero de la uni , pasate por mi perfil de GitHub mira algo mis repos si quieres y si me quieres contactar en el repositorio https://github.com/pxp9/pxp9 hay un issue donde tienes mi Telegram o Discord. 
¡ Muy chulas las páginas web !
Cierra este issue cuando lo leas o respondas.

**Comment by JLDEMIGUEL** [comment]
Me alegro de que haya gustado, mirare tu repositorio
